# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrailDigger < Formula
  desc "trail-digger is a tool for digging trail log files of AWS CloudTrail."
  homepage "https://github.com/pepabo/trail-digger"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pepabo/trail-digger/releases/download/v0.2.2/trail-digger_v0.2.2_darwin_arm64.zip"
      sha256 "1922604b4b02d36ebec5772af23784312c87f1a8a51931e326a16c2c8091e5c4"

      def install
        bin.install 'trail-digger'
        output = Utils.safe_popen_read("#{bin}/trail-digger", 'completion', 'bash')
        (bash_completion/'trail-digger').write output
        output = Utils.safe_popen_read("#{bin}/trail-digger", 'completion', 'zsh')
        (zsh_completion/'_trail-digger').write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pepabo/trail-digger/releases/download/v0.2.2/trail-digger_v0.2.2_darwin_amd64.zip"
      sha256 "71d6fd2b36904ffe830f406bef5a20238192e2e2e1ac457ceda619855597e51b"

      def install
        bin.install 'trail-digger'
        output = Utils.safe_popen_read("#{bin}/trail-digger", 'completion', 'bash')
        (bash_completion/'trail-digger').write output
        output = Utils.safe_popen_read("#{bin}/trail-digger", 'completion', 'zsh')
        (zsh_completion/'_trail-digger').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pepabo/trail-digger/releases/download/v0.2.2/trail-digger_v0.2.2_linux_amd64.tar.gz"
      sha256 "c72c6d6744405869307ad97c2903f1d04565e6fd0a342ad6dbe59ddd31ce4887"

      def install
        bin.install 'trail-digger'
        output = Utils.safe_popen_read("#{bin}/trail-digger", 'completion', 'bash')
        (bash_completion/'trail-digger').write output
        output = Utils.safe_popen_read("#{bin}/trail-digger", 'completion', 'zsh')
        (zsh_completion/'_trail-digger').write output
      end
    end
  end
end
