# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrailDigger < Formula
  desc "trail-digger is a tool for digging trail log files of AWS CloudTrail."
  homepage "https://github.com/pepabo/trail-digger"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pepabo/trail-digger/releases/download/v0.1.0/trail-digger_v0.1.0_darwin_arm64.zip"
      sha256 "77031cf393d5c31a3d7e7e2bf73081e7ef90af0eee077a45af5636344ca2fbad"

      def install
        bin.install 'trail-digger'
        output = Utils.safe_popen_read("#{bin}/trail-digger", 'completion', 'bash')
        (bash_completion/'trail-digger').write output
        output = Utils.safe_popen_read("#{bin}/trail-digger", 'completion', 'zsh')
        (zsh_completion/'_trail-digger').write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pepabo/trail-digger/releases/download/v0.1.0/trail-digger_v0.1.0_darwin_amd64.zip"
      sha256 "af4794d3f1dcbc5f654842f56bab5c6b53234a3a4eff70d16ae0e8d4b53c3462"

      def install
        bin.install 'trail-digger'
        output = Utils.safe_popen_read("#{bin}/trail-digger", 'completion', 'bash')
        (bash_completion/'trail-digger').write output
        output = Utils.safe_popen_read("#{bin}/trail-digger", 'completion', 'zsh')
        (zsh_completion/'_trail-digger').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pepabo/trail-digger/releases/download/v0.1.0/trail-digger_v0.1.0_linux_amd64.tar.gz"
      sha256 "6ff7feb64d43b5a2d87101496b3af2f40e2b69ab541d3fd8dc726b97f9e0fa5a"

      def install
        bin.install 'trail-digger'
        output = Utils.safe_popen_read("#{bin}/trail-digger", 'completion', 'bash')
        (bash_completion/'trail-digger').write output
        output = Utils.safe_popen_read("#{bin}/trail-digger", 'completion', 'zsh')
        (zsh_completion/'_trail-digger').write output
      end
    end
  end
end
